Create Order HomWork
mate-academy/hibernate-order-hw pull request #220
Opened 2022-06-01 14:52 UTC by yuriikozar

Solution + Checkstyle
v1

2022-06-03 09:51 UTC, irynahrynda approved these changes

2022-06-03 09:51 UTC, irynahrynda commented on src/main/java/mate/academy/model/Order.java
> +
delete empty line

2022-06-03 10:18 UTC, Sofasmile requested changes

2022-06-03 10:18 UTC, Sofasmile commented on src/main/java/mate/academy/model/Order.java
> +    private LocalDateTime orderDate;
we can add annotation to change the name of the colunm

2022-06-03 10:18 UTC, Sofasmile commented on src/main/java/mate/academy/service/impl/OrderServiceImpl.java
> +        order.setTickets(shoppingCart.getTickets());
we should create a new list of tickets
https://mate-academy.github.io/jv-program-common-mistakes/hibernate/add-order/add-order-hw#:~:text=When%20passing%20tickets,has%20been%20created.

2022-06-03 13:47 UTC, Sofasmile commented on src/main/java/mate/academy/service/impl/OrderServiceImpl.java
> +        order.setTickets(shoppingCart.getTickets());
sorry, in this case, all will be fine because you create an order and clear the list of tickets after that.
let's skip this comment

2022-06-07 14:01 UTC, KseniiaMakarova approved these changes

2024-02-15 18:24 UTC, closed without merging