first version of hibernate order homework
mate-academy/hibernate-order-hw pull request #501
Opened 2023-04-22 05:58 UTC by oleksiistepaniak

2023-04-22 11:07 UTC, De1eF approved these changes
I made the same mistake)

2023-04-22 11:07 UTC, De1eF commented on src/main/java/mate/academy/Main.java
> +    private static final MovieService movieService =
Either move initializations closer to their first use, or make them class variables

2023-04-22 11:07 UTC, De1eF commented on src/main/java/mate/academy/model/Order.java
> +    private User user;
Should be named via @JoinColumn

2023-04-24 08:22 UTC, petro-ushchuk requested changes

2023-04-24 08:22 UTC, petro-ushchuk commented on src/main/java/mate/academy/service/impl/OrderServiceImpl.java
> +        order.setTickets(shoppingCart.getTickets());
Check common mistakes and fix this line

2024-07-25 18:46 UTC, closed without merging