Hw hibernate order
mate-academy/hibernate-order-hw pull request #542
Opened 2023-05-14 16:56 UTC by Iskamele

2023-05-14 17:03 UTC, Iskamele commented
Do we have to display all entity information in the getOrdersHistory method?

They were especially considering that tickets are bought in the names of logged-in users.

2023-05-15 09:13 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-05-15 09:13 UTC, Rommelua commented on src/main/java/mate/academy/service/impl/OrderServiceImpl.java
> +    private static final LocalDateTime CURRENT_DATE_TIME = LocalDateTime.now();
How many times this constant will be initialized?
Will different orders have different times?

2023-05-15 10:44 UTC, Rommelua approved these changes

2026-01-14 09:22 UTC, closed without merging